name: to_do_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0+1
  shadcn_flutter: ^0.0.24
  bootstrap_icons: ^1.11.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: GeistSans
      fonts:
        - asset: packages/shadcn_flutter/fonts/Geist-Black.otf
          weight: 800
        - asset: packages/shadcn_flutter/fonts/Geist-Bold.otf
          weight: 700
        - asset: packages/shadcn_flutter/fonts/Geist-Light.otf
          weight: 300
        - asset: packages/shadcn_flutter/fonts/Geist-Medium.otf
          weight: 500
        - asset: packages/shadcn_flutter/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: packages/shadcn_flutter/fonts/Geist-Thin.otf
          weight: 100
        - asset: packages/shadcn_flutter/fonts/Geist-UltraBlack.otf
          weight: 900
        - asset: packages/shadcn_flutter/fonts/Geist-UltraLight.otf
          weight: 200
        - asset: packages/shadcn_flutter/fonts/Geist-Regular.otf
          weight: 400
    - family: GeistMono
      fonts:
        - asset: packages/shadcn_flutter/fonts/GeistMono-Black.otf
          weight: 800
        - asset: packages/shadcn_flutter/fonts/GeistMono-Bold.otf
          weight: 700
        - asset: packages/shadcn_flutter/fonts/GeistMono-Light.otf
          weight: 300
        - asset: packages/shadcn_flutter/fonts/GeistMono-Medium.otf
          weight: 500
        - asset: packages/shadcn_flutter/fonts/GeistMono-Regular.otf
          weight: 400
        - asset: packages/shadcn_flutter/fonts/GeistMono-SemiBold.otf
          weight: 600
        - asset: packages/shadcn_flutter/fonts/GeistMono-Thin.otf
          weight: 100
        - asset: packages/shadcn_flutter/fonts/GeistMono-UltraBlack.otf
          weight: 900
        - asset: packages/shadcn_flutter/fonts/GeistMono-UltraLight.otf
          weight: 200
    - family: RadixIcons
      fonts:
        - asset: packages/shadcn_flutter/icons/RadixIcons.otf
